name: study_group_manager
description: A Flutter app for managing study groups with AI, DEV, and OS categories.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Image & File Selection
  image_picker: ^1.0.4
  file_picker: ^6.1.1

  # Image Caching
  cached_network_image: ^3.3.0

  # HTTP Requests
  http: ^1.1.0

  # Path Provider
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Remove asset references for now - we'll add them later if needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Remove custom fonts - we'll use default Material Design fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700